P4_SRCS = ../int_md.p4
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = tcp-linear5-topo.json
EXTRA_ARG = s1 ./my_controller.py
COLLECTOR_HOST = h_report
NOISE_COMMANDS = echo "h2 ./receive.py &";
SENDER_ARGS = 10.0.5.5

include ../../../utils/Makefile