# SPDX-License-Identifier: Apache-2.0
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = linear10-topo.json
SENDER_HOST = h1
COLLECTOR_HOST = h3
SENDER_ARGS = 10.0.10.10 "Hello"
EXTRA_ARG = s1 ./my_controller.py --topo-size 10

# Assuming the utils directory is two levels up
include ../../../utils/Makefile