# SPDX-License-Identifier: Apache-2.0
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = linear3-topo.json
SENDER_HOST = h1
COLLECTOR_HOST = h3

# Assuming the utils directory is two levels up
include ../../../utils/Makefile