# SPDX-License-Identifier: Apache-2.0
BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = linear20-topo.json
SENDER_HOST = h1
COLLECTOR_HOST = h3
SENDER_ARGS = 10.0.20.20 "Hello"
EXTRA_ARG = s1 ./my_controller.py --topo-size 2

# Assuming the utils directory is two levels up
include ../../../utils/Makefile